[package]
name = "kay"
description = "Experimental high-performance actor system framework for Rust"
version = "0.1.0"
authors = ["Anselm Eickhoff <anselm.eickhoff@gmail.com>"]
repository = "https://github.com/aeickhoff/kay"
license = "MIT"
maintenance = { status = "experimental" }

[dependencies]
byteorder = "1"
chunky = "0.1.0"
compact = "0.1.0"
compact_macros = "0.1.0"